apiVersion: v1
kind: Secret
metadata:
  name: pctasks-sa-token
  annotations:
    # Service account created by Argo, name
    # set in argo-values.yaml
    kubernetes.io/service-account.name: pctasks-sa
type: kubernetes.io/service-account-token